"""add assessment_response model

Revision ID: a16fce3e2d5b
Revises: d57c99a3d012
Create Date: 2025-10-08 18:33:43.482611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16fce3e2d5b'
down_revision: Union[str, Sequence[str], None] = 'd57c99a3d012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_email_verify_token_hash', 'email_verify_tokens', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email_verify_token_hash', 'email_verify_tokens', type_='unique')
    # ### end Alembic commands ###
