"""auto uuid gen

Revision ID: f9f7930a42f7
Revises: 9a1b2c3d4e5f
Create Date: 2025-10-20 09:28:41.150753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9f7930a42f7'
down_revision: Union[str, Sequence[str], None] = '9a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_assessment_responses_item_id'), 'assessment_responses', type_='unique')
    op.add_column('document_chunks', sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_unique_constraint(op.f('uq_email_verify_tokens_token_hash'), 'email_verify_tokens', ['token_hash'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_email_verify_tokens_token_hash'), 'email_verify_tokens', type_='unique')
    op.drop_column('document_chunks', 'embedding')
    op.create_unique_constraint(op.f('uq_assessment_responses_item_id'), 'assessment_responses', ['item_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
